[package]
name = "crdb-cache"
version = "0.0.1"
edition = "2021"

[dependencies]
crdb-core.workspace = true

anyhow.workspace = true
serde_json.workspace = true
waaaa.workspace = true
web-time.workspace = true

[dev-dependencies]
getrandom-0-2 = { workspace = true, features = ["js"] }
