[package]
name = "crdb"
version = "0.1.0"
edition = "2021"
license = "AGPL3"

[package.metadata.docs.rs]
all-features = true

[features]
client = ["paste"]
server = ["axum", "sqlx"]

[dependencies]
anyhow = "1.0"
futures = "0.3.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.35", features = ["rt", "sync"] }
tracing = "0.1.40"
ulid = "1.1"

# Server dependencies
axum = { version = "0.7.2", optional = true }
sqlx = { version = "0.7.3", features = ["postgres"], optional = true }

# Client dependencies
paste = { version = "1.0", optional = true }
