[package]
name = "crdb"
version = "0.1.0"
edition = "2021"
license = "AGPL3"

[package.metadata.docs.rs]
all-features = true

[features]
client-js = ["client", "getrandom/js", "indexed_db_futures"]
client-native = ["client", "sqlx/sqlite"]

client = ["paste"]
server = ["axum", "sqlx/json", "sqlx/postgres", "sqlx/uuid", "uuid"]

[dependencies]
anyhow = "1.0"
async-stream = "0.3.5"
deepsize = "0.2.0"
educe = "0.5.9"
futures = "0.3.29"
getrandom = "0.2.11"
reord = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.10.8"
thiserror = "1.0"
tokio = { version = "1.35", features = ["rt", "sync"] }
tracing = "0.1.40"
ulid = "1.1"

# Optional dependencies
axum = { version = "0.7.2", optional = true }
indexed_db_futures = { version = "0.4.1", optional = true }
paste = { version = "1.0", optional = true }
# Note that this patch is https://github.com/launchbadge/sqlx/pull/2961.
# It is not useful for production, but local development and esp. testing do require it.
# So, the solution of just using it here should work fine for now.
sqlx = { version = "0.7.3", features = ["runtime-tokio"], optional = true, git = "https://github.com/Ekleog/sqlx", rev = "f007dd901e835e7cbecb0c104982eb775d5556c3" }
uuid = { version = "1.6", optional = true }

[dev-dependencies]
bolero = "0.10.0"
reord = { version = "0.1.0", features = ["test"] }
