[package]
name = "crdb"
version = "0.1.0"
edition = "2021"
license = "AGPL3"

[package.metadata.docs.rs]
all-features = true

[features]
client = [
    "paste",
    "sqlx/sqlite",
    "sqlx/uuid",
]
server = [
    "axum",
    "cron",
    "lockable",
    "rand",
    "sqlx/rust_decimal",
    "sqlx/json",
    "sqlx/postgres",
    "sqlx/uuid",
]
_tests = [ # internal feature, for use by wasm tests in particular and thus all tests from there on
    "arbitrary",
    "arbitrary-json",
    "bolero",
    "rand",
    "tracing-wasm",
]

[dependencies]
anyhow = "1.0"
async-broadcast = "0.5.0"
async-stream = "0.3.5"
chrono = "0.4.31"
deepsize = "0.2.0"
educe = "0.5.9"
futures = "0.3.29"
icu_casemap = "1.4"
icu_normalizer = "1.4"
icu_properties = "1.4"
icu_segmenter = "1.4"
reord = "0.2.2"
rust_decimal = { version = "1.33", features = ["serde-arbitrary-precision"] }
rust-stemmers = "1.2"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
sha3 = "0.10.8"
thiserror = "1.0"
tokio = { version = "1.35", features = ["macros", "rt", "sync"] }
tokio-util = "0.7.10"
tracing = "0.1.40"
ulid = { version = "1.1", features = ["serde"] }
writeable = "0.5.4"

# Optional dependencies
axum = { version = "0.7.2", optional = true }
cron = { version = "0.12.0", optional = true }
lockable = { version = "0.0.7", optional = true }
paste = { version = "1.0", optional = true }
rand = { version = "0.8.5", optional = true }

# Optional dependencies, for tests
arbitrary = { version = "1.3", features = ["derive"], optional = true }
arbitrary-json = { version = "=0.1.1", optional = true } # very small crate, can we actually trust updates?
bolero = { version = "0.10.0", features = ["arbitrary"], optional = true }
console_error_panic_hook = "0.1.7"
tracing-wasm = { version = "0.2.1", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.11", features = ["js"] }
gloo-net = "0.5.0"
indexed-db = "0.3.4"
js-sys = "0.3.67"
parking_lot = { version = "0.11", features = ["wasm-bindgen"] }
serde-wasm-bindgen = "0.6.3"
wasm-bindgen = "0.2.90"
wasm-bindgen-futures = "0.4.39"
wasm-timer = "0.2.5"
web-sys = { version = "0.3.66", features = ["DomException", "Event", "IdbDatabase", "IdbFactory", "IdbIndex", "IdbObjectStore", "IdbObjectStoreParameters", "IdbOpenDbRequest", "IdbTransaction", "IdbTransactionMode", "Navigator", "StorageManager", "Window"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sqlx = { version = "0.7.3", features = ["runtime-tokio"] }
tokio-tungstenite = "0.21.0"
uuid = "1.6"

[dev-dependencies]
num-bigint = { version = "0.4.4", features = ["arbitrary"] }
reord = { version = "0.2.2", features = ["test"] }
rust_decimal = { version = "1.33", features = ["rust-fuzz"] }
tempfile = "3.9"
tracing-subscriber = "0.3.18"
wasm-bindgen-test = "0.3.39"
web-sys = { version = "0.3.66", features = ["console"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1.35", features = ["full"] }

[profile.fuzz]
inherits = "dev"
opt-level = 3
incremental = false
codegen-units = 1
