[package]
name = "crdb"
version = "0.1.0"
edition = "2021"
license = "AGPL3"

[package.metadata.docs.rs]
all-features = true

[features]
client-js = ["getrandom/js", "indexed_db_futures", "paste"]
client-native = ["paste", "sqlx/sqlite"]
server = ["axum", "sqlx/postgres"]

[dependencies]
anyhow = "1.0"
deepsize = "0.2.0"
futures = "0.3.29"
getrandom = "0.2.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.10.8"
tokio = { version = "1.35", features = ["rt", "sync"] }
tracing = "0.1.40"
ulid = "1.1"

# Optional dependencies
axum = { version = "0.7.2", optional = true }
indexed_db_futures = { version = "0.4.1", optional = true }
paste = { version = "1.0", optional = true }
sqlx = { version = "0.7.3", optional = true }

[dev-dependencies]
bolero = "0.10.0"
