[package]
name = "crdb"
version = "0.1.0"
edition = "2021"
license = "AGPL3"

[package.metadata.docs.rs]
all-features = true

[features]
client = ["paste", "sqlx/sqlite", "sqlx/uuid"]
server = ["axum", "lockable", "rand", "sqlx/json", "sqlx/postgres", "sqlx/uuid"]

[dependencies]
anyhow = "1.0"
async-stream = "0.3.5"
deepsize = "0.2.0"
educe = "0.5.9"
futures = "0.3.29"
reord = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.10.8"
thiserror = "1.0"
tokio = { version = "1.35", features = ["rt", "sync"] }
tracing = "0.1.40"
ulid = { version = "1.1", features = ["serde"] }

# Optional dependencies
axum = { version = "0.7.2", optional = true }
lockable = { version = "0.0.7", optional = true }
paste = { version = "1.0", optional = true }
rand = { version = "0.8.5", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.11", features = ["js"] }
indexed_db_futures = "0.4.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sqlx = { version = "0.7.3", features = ["runtime-tokio"] }
uuid = "1.6"

[dev-dependencies]
bolero = "0.10.0"
reord = { version = "0.1.4", features = ["test"] }
tempfile = "3.9"
tokio = { version = "1.35", features = ["full"] }

[profile.fuzz]
inherits = "dev"
opt-level = 3
incremental = false
codegen-units = 1
