[package]
name = "crdb"
version = "0.1.0"
edition = "2021"
license = "AGPL3"

[package.metadata.docs.rs]
all-features = true

[features]
client = ["uuid/v4"]
server = ["axum", "sqlx", "tokio", "tracing"]

[dependencies]
anyhow = "1.0"
futures = "0.3.29"
serde = "1.0"
serde_json = "1.0"
uuid = "1.6"

# Server dependencies
axum = { version = "0.7.2", optional = true }
sqlx = { version = "0.7.3", features = ["postgres"], optional = true }
tokio = { version = "1.35", optional = true }
tracing = { version = "0.1.40", optional = true }
