[package]
name = "crdb"
version = "0.1.0"
edition = "2021"
license = "AGPL3"

[package.metadata.docs.rs]
all-features = true

[features]
client-js = ["client", "getrandom/js", "indexed_db_futures"]
client-native = ["client", "sqlx/sqlite"]

client = ["paste"]
server = ["axum", "sqlx/json", "sqlx/postgres", "sqlx/uuid", "uuid"]

[dependencies]
anyhow = "1.0"
deepsize = "0.2.0"
educe = "0.5.9"
futures = "0.3.29"
getrandom = "0.2.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.10.8"
thiserror = "1.0"
tokio = { version = "1.35", features = ["rt", "sync"] }
tracing = "0.1.40"
ulid = "1.1"

# Optional dependencies
axum = { version = "0.7.2", optional = true }
indexed_db_futures = { version = "0.4.1", optional = true }
paste = { version = "1.0", optional = true }
sqlx = { version = "0.7.3", features = ["runtime-tokio"], optional = true }
uuid = { version = "1.6", optional = true }

[dev-dependencies]
bolero = "0.10.0"
