[package]
name = "crdb"
version = "0.1.0"
edition = "2021"
license = "AGPL3"

[features]
server = ["anyhow", "axum", "sqlx", "tokio", "tracing"]

[dependencies]
# Server dependencies
anyhow = { version = "1.0", optional = true }
axum = { version = "0.7.2", optional = true }
sqlx = { version = "0.7.3", features = ["postgres"], optional = true }
tokio = { version = "1.35", optional = true }
tracing = { version = "0.1.40", optional = true }
