[toolchain]
channel = "nightly-2024-02-16" # TODO(blocked): switch back to a stable release as soon as RPITIT lands
components = ["clippy", "rustfmt", "rust-analyzer"]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
