[toolchain]
channel = "nightly-2023-12-23" # TODO: switch back to a stable release as soon as RPITIT lands
components = ["rustfmt", "rust-analyzer"]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
