[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../api" }
crdb = { path = "../../..", features = ["server"] }
tokio = { version = "1.0", features = ["full"] }
