[package]
name = "crdb"
version = "0.1.0"
edition = "2021"
license = "AGPL3"

[package.metadata.docs.rs]
all-features = true

[features]
client = [
    "async-stream",
    "crdb-cache",
    "crdb-indexed-db",
    "crdb-sqlite",
    "gloo-net",
    "tokio-tungstenite",
    "tokio-util",
]
server = [ "crdb-server" ]

[dependencies]
crdb-core.workspace = true
crdb-helpers.workspace = true
crdb-macros.workspace = true

anyhow.workspace = true
bitflags.workspace = true
chrono.workspace = true
deepsize.workspace = true
educe.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
ulid.workspace = true
web-time.workspace = true

# Optional dependencies
crdb-cache = { workspace = true, optional = true }
crdb-server = { workspace = true, optional = true }

async-stream = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
crdb-indexed-db = { workspace = true, optional = true }
getrandom = { workspace = true, features = ["js"] } # TODO(api-high): introduce a `js` feature here too and enable conditionally
gloo-net = { workspace = true, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
crdb-sqlite = { workspace = true, optional = true }
tokio-tungstenite = { workspace = true, optional = true }
