[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../api" }
crdb = { path = "../../..", features = ["client"] }

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2.11", features = ["js"] }
