[package]
name = "basic-client-js"
version = "0.1.0"
edition = "2021"

[dependencies]
basic-api = { path = "../api" }
console_error_panic_hook = "0.1.7"
crdb = { path = "../../..", features = ["client"] }
tracing-wasm = "0.2.1"
yew = { version = "0.21.0", features = ["csr"] }
web-sys = "0.3.66"
