[package]
name = "crdb-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
crdb-core.workspace = true
crdb-helpers.workspace = true
serde.workspace = true
serde_json.workspace = true
waaaa.workspace = true
