use super::ObjectCache;
use crate::{
    db_trait::{Db, DynNewEvent, DynNewObject, DynNewRecreation},
    CanDoCallbacks, CrdbFuture,
};

pub trait CacheConfig {
    /// Auto-generated by `crdb::db!`.
    ///
    /// Calls `cache`'s `create` method with the proper type and the fields from `o`.
    fn create(
        cache: &mut ObjectCache,
        o: DynNewObject,
    ) -> impl CrdbFuture<Output = crate::Result<bool>>;

    /// Auto-generated by `crdb::db!`.
    ///
    /// Calls `cache`'s `submit` method with the proper type and the fields from `o`.
    fn submit(
        cache: &mut ObjectCache,
        e: DynNewEvent,
    ) -> impl CrdbFuture<Output = crate::Result<bool>>;

    /// Auto-generated by `crdb::db!`.
    ///
    /// Calls `cache`'s `recreate` method with the proper type and the fields from `s`.
    fn recreate(
        cache: &mut ObjectCache,
        s: DynNewRecreation,
    ) -> impl CrdbFuture<Output = crate::Result<()>>;

    /// Auto-generated by `crdb::db!`.
    ///
    /// Calls `cache`'s `create` method with the proper type and the fields from `o`.
    fn create_in_db<D: Db, C: CanDoCallbacks>(
        db: &D,
        o: DynNewObject,
        lock: bool,
        cb: &C,
    ) -> impl CrdbFuture<Output = crate::Result<()>>;

    /// Auto-generated by `crdb::db!`.
    ///
    /// Calls `cache`'s `submit` method with the proper type and the fields from `o`.
    fn submit_in_db<D: Db, C: CanDoCallbacks>(
        db: &D,
        e: DynNewEvent,
        cb: &C,
    ) -> impl CrdbFuture<Output = crate::Result<()>>;

    /// Auto-generated by `crdb::db!`.
    ///
    /// Calls `cache`'s `recreate` method with the proper type and the fields from `s`.
    fn recreate_in_db<D: Db, C: CanDoCallbacks>(
        db: &D,
        s: DynNewRecreation,
        cb: &C,
    ) -> impl CrdbFuture<Output = crate::Result<()>>;
}
