name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  DATABASE_URL: "postgres://postgres:postgres@localhost/crdb-test"

jobs:
  just-test:
    strategy:
      matrix:
        include:
          - name: Tests
            command: just test
          - name: Build All Features
            command: cargo hack build --workspace --ignore-private --no-dev-deps --feature-powerset --optional-deps --depth 4
          - name: Clippy All Features
            command: cargo hack clippy --workspace --ignore-private --no-dev-deps --feature-powerset --optional-deps --depth 4
          - name: Test All Features
            command: cargo hack test --workspace --ignore-private --feature _tests --feature-powerset --optional-deps --depth 3
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install cargo dependencies
      - uses: taiki-e/install-action@6943331e01261cdff7420bbc2508cb463574e404
        with:
          tool: just, cargo-nextest, cargo-hack
      # TODO(misc-low): contribute these to taiki-e/install-action upstream?
      - uses: baptiste0928/cargo-install@1cd874a5478fdca35d868ccc74640c5aabbb8f1b
        with:
          crate: sqlx-cli
      - uses: baptiste0928/cargo-install@1cd874a5478fdca35d868ccc74640c5aabbb8f1b
        with:
          crate: wasm-bindgen-cli

      # Setup sccache, that'll share build artifacts with all the target directories
      - uses: mozilla-actions/sccache-action@2e7f9ec7921547d4b46598398ca573513895d0bd
      - run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      # Setup chromedriver for client-js tests
      - uses: nanasess/setup-chromedriver@42cc2998329f041de87dc3cfa33a930eacd57eaa
      - run: sudo Xvfb -ac :0 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      # Setup postgresql for server tests
      - uses: ikalnytskyi/action-setup-postgres@74e396491e76c84f8ad92a4f5a69ab0deb75bbc2
        with:
          username: postgres
          password: postgres
          database: crdb-test
      - run: sqlx migrate run --source crdb/src/server/migrations

      # Run the tests
      - run: ${{ matrix.command }}

  just-clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@6943331e01261cdff7420bbc2508cb463574e404
        with:
          tool: just
      - run: just clippy

  just-udeps:
    name: Udeps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@6943331e01261cdff7420bbc2508cb463574e404
        with:
          tool: just, cargo-udeps
      - run: just udeps

  just-doc:
    name: Doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@6943331e01261cdff7420bbc2508cb463574e404
        with:
          tool: just
      - run: just doc
