name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  DATABASE_URL: "postgres://postgres:postgres@localhost/crdb"

jobs:
  just-test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install cargo dependencies
      - uses: taiki-e/install-action@91af8c38814c3998cb755869e5cbeffd3ab0e462
        with:
          tool: just, cargo-nextest
      # TODO(low): contribute these to taiki-e/install-action upstream?
      - uses: baptiste0928/cargo-install@21a18ba3bf4a184d1804e8b759930d3471b1c941
        with:
          crate: sqlx-cli
      - uses: baptiste0928/cargo-install@21a18ba3bf4a184d1804e8b759930d3471b1c941
        with:
          crate: wasm-bindgen-cli

      # Setup sccache, that'll share build artifacts with all the target directories
      - uses: mozilla-actions/sccache-action@2e7f9ec7921547d4b46598398ca573513895d0bd
      - run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      # Setup chromedriver for client-js tests
      - uses: nanasess/setup-chromedriver@480d644e773cd6d53e4cb76557c8ad5e5806d7da
      - run: sudo Xvfb -ac :0 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      # Setup postgresql for server tests
      - uses: ikalnytskyi/action-setup-postgres@74e396491e76c84f8ad92a4f5a69ab0deb75bbc2
        with:
          username: postgres
          password: postgres
          database: crdb
      - run: sqlx migrate run --source src/server/migrations

      # Run the tests
      - run: just test

  just-clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@91af8c38814c3998cb755869e5cbeffd3ab0e462
        with:
          tool: just
      - run: just clippy

  just-udeps:
    name: Udeps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@91af8c38814c3998cb755869e5cbeffd3ab0e462
        with:
          tool: just, cargo-udeps
      - run: just udeps

  just-doc:
    name: Doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@91af8c38814c3998cb755869e5cbeffd3ab0e462
        with:
          tool: just
      - run: just doc
