name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  just-test:
    name: just test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baptiste0928/cargo-install@21a18ba3bf4a184d1804e8b759930d3471b1c941
        with:
          crate: just
      - uses: baptiste0928/cargo-install@21a18ba3bf4a184d1804e8b759930d3471b1c941
        with:
          crate: cargo-nextest
      - uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43
      - uses: ikalnytskyi/action-setup-postgres@510dee7c6d0b2cdf7d94d3f983aefd7f39ecf342
        with:
          username: postgres
          password: postgres
          database: postgres
      - run: DATABASE_URL="postgres://postgres:postgres@localhost/postgres" just test
